import PDFDocument from 'pdfkit';
import { CaseReportData } from '../../src/types/index.js';

export class ReportGeneratorService {
  /**
   * Generates a formatted PDF report stream for a DeepShield Case.
   */
  public static generatePdf(data: CaseReportData): PDFKit.PDFDocument {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });

    // Colors
    const primaryColor = '#0f172a'; // Navy 800
    const accentColor = '#4f46e5';  // Brand Indigo
    const textColor = '#334155';    // Slate 700

    // Title / Header Banner
    doc
      .rect(40, 40, 515, 60)
      .fill(primaryColor);

    doc
      .fillColor('#ffffff')
      .fontSize(20)
      .font('Helvetica-Bold')
      .text('DEEPSHIELD EVIDENCE REPORT', 55, 55);

    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#94a3b8')
      .text('AI-Assisted Cyber-Harassment Evidence Case Document', 55, 80);

    // Disclaimer Box
    doc
      .rect(40, 110, 515, 36)
      .fillAndStroke('#fef3c7', '#f59e0b');

    doc
      .fillColor('#92400e')
      .fontSize(8)
      .font('Helvetica-Bold')
      .text('PROTOTYPE DISCLAIMER:', 50, 116)
      .font('Helvetica')
      .text(
        'AI-assisted analysis requiring human verification. This document is generated by a prototype system for organizational assistance and does not constitute a forensic or legal determination of criminal guilt.',
        50,
        127,
        { width: 495 }
      );

    let y = 160;

    // Case Information
    doc
      .fillColor(primaryColor)
      .fontSize(14)
      .font('Helvetica-Bold')
      .text('1. Case Overview', 40, y);

    y += 20;

    doc
      .fontSize(10)
      .font('Helvetica-Bold').fillColor(textColor).text('Case ID: ', 40, y)
      .font('Helvetica').text(data.caseInfo.id, 110, y);
    
    doc
      .font('Helvetica-Bold').text('Title: ', 260, y)
      .font('Helvetica').text(data.caseInfo.title, 310, y);

    y += 16;

    doc
      .font('Helvetica-Bold').text('Category: ', 40, y)
      .font('Helvetica').text(data.caseInfo.category, 110, y);

    doc
      .font('Helvetica-Bold').text('Status: ', 260, y)
      .font('Helvetica').text(data.caseInfo.status, 310, y);

    y += 16;

    doc
      .font('Helvetica-Bold').text('Created: ', 40, y)
      .font('Helvetica').text(new Date(data.caseInfo.createdAt).toLocaleString(), 110, y);

    y += 24;
    doc.rect(40, y, 515, 1).fill('#e2e8f0');
    y += 12;

    // Evidence Summary Section
    doc
      .fillColor(primaryColor)
      .fontSize(14)
      .font('Helvetica-Bold')
      .text(`2. Evidence Inventory (${data.evidenceList.length} items)`, 40, y);

    y += 20;

    // Table Header
    doc
      .rect(40, y, 515, 20)
      .fill('#f1f5f9');

    doc
      .fillColor('#1e293b')
      .fontSize(9)
      .font('Helvetica-Bold')
      .text('ID', 45, y + 5)
      .text('Type', 110, y + 5)
      .text('Source', 180, y + 5)
      .text('Date', 250, y + 5)
      .text('Risk Level', 340, y + 5)
      .text('Status', 440, y + 5);

    y += 22;

    data.evidenceList.forEach((ev) => {
      if (y > 720) {
        doc.addPage();
        y = 40;
      }

      doc
        .fontSize(8)
        .font('Helvetica')
        .fillColor(textColor)
        .text(ev.id, 45, y)
        .text(ev.type, 110, y)
        .text(ev.source, 180, y)
        .text(ev.date, 250, y)
        .font('Helvetica-Bold')
        .fillColor(ev.riskLevel === 'CRITICAL' || ev.riskLevel === 'HIGH' ? '#dc2626' : '#059669')
        .text(ev.riskLevel, 340, y)
        .fillColor(textColor)
        .font('Helvetica')
        .text(ev.analysisStatus, 440, y);

      y += 16;
    });

    y += 12;
    if (y > 680) {
      doc.addPage();
      y = 40;
    }

    doc.rect(40, y, 515, 1).fill('#e2e8f0');
    y += 12;

    // AI Analysis Summary
    doc
      .fillColor(primaryColor)
      .fontSize(14)
      .font('Helvetica-Bold')
      .text('3. AI Analysis & Indicator Summary', 40, y);

    y += 20;

    data.analyses.forEach((analysis) => {
      if (y > 700) {
        doc.addPage();
        y = 40;
      }

      doc
        .fontSize(9)
        .font('Helvetica-Bold')
        .fillColor(accentColor)
        .text(`Evidence ID: ${analysis.evidenceId}`, 40, y);

      y += 14;

      doc
        .fontSize(8)
        .font('Helvetica-Bold').fillColor(textColor).text('Risk Rating: ', 50, y)
        .font('Helvetica').text(`${analysis.riskLevel} (Score: ${analysis.score}/100 | Confidence: ${analysis.confidence}%)`, 120, y);

      y += 12;

      doc
        .font('Helvetica-Bold').text('Indicators: ', 50, y)
        .font('Helvetica').text(analysis.keyIndicators.join('; '), 120, y, { width: 420 });

      y += 16;
    });

    // Human Review Section
    if (data.reviews.length > 0) {
      if (y > 650) {
        doc.addPage();
        y = 40;
      }

      y += 10;
      doc.rect(40, y, 515, 1).fill('#e2e8f0');
      y += 12;

      doc
        .fillColor(primaryColor)
        .fontSize(14)
        .font('Helvetica-Bold')
        .text('4. Human-in-the-Loop Review Audit Log', 40, y);

      y += 20;

      data.reviews.forEach((rev) => {
        if (y > 700) {
          doc.addPage();
          y = 40;
        }

        doc
          .fontSize(9)
          .font('Helvetica-Bold')
          .fillColor('#059669')
          .text(`Reviewer: ${rev.reviewerName} | Action: ${rev.action}`, 40, y);

        y += 14;

        doc
          .fontSize(8)
          .font('Helvetica')
          .fillColor(textColor)
          .text(`Evidence: ${rev.evidenceId} | Original Risk: ${rev.originalRisk} → Final Risk: ${rev.finalRisk}`, 50, y);

        y += 12;

        doc
          .font('Helvetica-Oblique')
          .text(`Notes: "${rev.notes}"`, 50, y, { width: 480 });

        y += 18;
      });
    }

    // Footer on all pages
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      doc
        .fontSize(8)
        .font('Helvetica')
        .fillColor('#94a3b8')
        .text(
          `Page ${i + 1} of ${range.count}  •  DeepShield Women Evidence Report  •  Generated ${new Date().toLocaleDateString()}`,
          40,
          790,
          { align: 'center', width: 515 }
        );
    }

    return doc;
  }
}
